//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSCare.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSCare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,location_type,parent_station,zone_id
        ///1,38831,בי&apos;&apos;ס בר לב/בן יהודה,רחוב: בן יהודה 74 עיר: כפר סבא רציף:  קומה: ,32.183985,34.917554,0,,38831
        ///2,38832,הרצל/צומת בילו,רחוב: הרצל עיר: קרית עקרון רציף:  קומה: ,31.870034,34.819541,0,,38832
        ///3,38833,הנחשול/הדייגים,רחוב: הנחשול 30 עיר: ראשון לציון רציף:  קומה: ,31.984553,34.782828,0,,38833
        ///4,38834,משה פריד/יצחק משקה,רחוב: משה פריד 5 עיר: רחובות רציף:  קומה: ,31.888325,34.790700,0,,38834
        ///6,38836,ת. מרכזית לו [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stops {
            get {
                return ResourceManager.GetString("stops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,location_type,parent_station,zone_id
        ///1,38831,בי&apos;&apos;ס בר לב/בן יהודה,רחוב: בן יהודה 74 עיר: כפר סבא רציף:  קומה: ,32.183985,34.917554,0,,38831.
        /// </summary>
        internal static string stops2 {
            get {
                return ResourceManager.GetString("stops2", resourceCulture);
            }
        }
    }
}
